---
- name: check the status of all services running in ansible tower
  hosts: 10.0.3.15
  tasks:
    - name: check the services
      command: "{{ item }}"
      loops:
        - automation-controller-services status
