---
- name: create inventory script
  hosts: localhost
  tasks:
    - name: create inventory
      file: 
        name: inventory.txt
        state: touch
    - blockinfile:
        path: "/root/inventory.txt"
        block: |
          - servera
          - serverb
          - serverc
          - serverd
          
      

