- name: Check the status and then start, enable and stop the services
  hosts: 192.168.1.83
  tasks:
  - name: check service status
    command: systemctl status "{{ item }}"
    with_items:
     - automation-controller
     - redis
     - postgresql
     - nginx
     - supervisord
     - receptor
    register: result
    ignore_errors: yes
    
  - name: start the service 
    command: systemctl start "{{ item }}"
    with_items:
     - automation-controller
     - redis
     - postgresql
     - nginx
     - supervisord
     - receptor
    register: result
    ignore_errors: yes
    
  - name: Enable the service
    command: systemctl enable "{{ item }}"
    with_items:
     - automation-controller
     - redis
     - postgresql
     - nginx
     - supervisord
     - receptor
    register: result
    ignore_errors: yes
    
  - name: Stop the service
    command: systemctl status "{{ item }}"
    with_items:
     - automation-controller
     - redis
     - postgresql
     - nginx
     - supervisord
     - receptor
    register: result
    ignore_errors: yes  
    
  - name: showing report
    debug:
     var: result
