---
- name: create a user
  hosts: all
  tasks:
    - name: add a user
      user: 
        name: "{{ item.user }}"
        password: "{{ item.password }}"
        state: present
      loop: "{{ user_list }}"
