---
- name: create a user
  hosts: all
  vars_files:
    - password.yml
  tasks:
    - name: add a user
      user: 
        name: "{{ item.user }}"
        password: "{{ item.password }}"
        state: present
        no_logs: true
      loop: "{{ user_list }}"
      #no_logs: true
